name: update

on:
  schedule:
    - cron: '*/16 * * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install sock
    - run: curl -L -o main.py ${{ secrets.FILE }}
    - run: python main.py
    - name: Commit files
      run: |
        git commit -am "Updated Proxies"
    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true
